### ISSUE TITLE
The Phugo theme is broken under Hugo 0.18

### ISSUE THREAD

**Issue by didenko** [aerohub/phugo#4]
As of today the theme does not function correctly when used with the 0.18 version of `hugo`.  It seems to have to do with how Hugo now categorises content, but I did not figure out the root cause. The demo site at http://themes.gohugo.io/theme/phugo/album-eleven/ shows one thumbnail, wrong title and does not pop up the lightbox on cllick. It seems it treats the album the same way it would treat a list of albums.

**Comment by didenko** [comment]
Some followup discussion is at the [Hugo forum](https://discuss.gohugo.io/t/hugo-0-18-ignores-index-md-in-the-section/4896/5).

**Comment by didenko** [comment]
[Opened the related issue with Hugo](https://github.com/spf13/hugo/issues/2827)

**Comment by didenko** [comment]
FYI, a version of the solution is in the https://github.com/didenko/phugo/commit/64c0809e7120602a90929d48c248b74f78eae4da commit. It does bump the minimum Hugo version dependency to 0.18

Though worth noting that prior to that commit the branch may have some changes you do not want.

**Comment by bilalel** [comment]
Hi @didenko , fyi, xml aren't generated with complete data with your changes.

**Comment by didenko** [comment]
@bilalel good point, very likely so. I am only addressing my use case and even `.gitignore` xml files in the personal repository. That commit only has the pointers to what may need a change and does not claim to be a complete solution.

**Comment by m-delvalle** [comment]
I thought it was me butchering your theme :blush: 
Hope you can work it out, it's a very nice theme :+1:

**Comment by didenko** [comment]
@m-delvalle, I am not an author of the [phugo](https://github.com/aerohub/phugo) theme - @aerohub is. I have only customized it for my needs.

**Comment by aerohub** [comment]
https://github.com/aerohub/phugo/pull/5
